sudo: false
env:
  global:
    - DOMAIN=localhost
    - JAVASCRIPT_DRIVER=headless_chrome
    - MAILER_SENDER=localhost
    - PORT=3000
    - RUN_SIMPLECOV=false
language: ruby
addons:
  postgresql: 9.4
cache:
  bundler: true
rvm:
  - 2.5.0
before_install:
  - gem install bundler -v 1.16.1
script:
  - bundle exec rspec
