version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "8080:80"
    environment:
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASS: "MVPwu1314.."
      DB_HOST: "db.ywbaswvhrdnjdavgryvl.supabase.co"
      DB_PORT: "5432"
      FORCE_SSL: "false"
      SECRET_KEY_BASE: "MVPwu1314.."
      RAILS_ENV: "production"
      RACK_ENV: "production"
