version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "8080:80"
    environment:
      DB_NAME: ""
      DB_USER: ""
      DB_PASS: ""
      DB_HOST: ""
      DB_PORT: ""
      FORCE_SSL: "false"
      SECRET_KEY_BASE: ""
      RAILS_ENV: "production"
      RACK_ENV: "production"
