languages:
  automatically: Automatically
  clojure: Clojure
  coffeescript: CoffeeScript
  crystal: Crystal
  css: CSS
  d: D
  dart: Dart
  django: Django
  dockerfile: Dockerfile
  elm: Elm
  erlang: Erlang
  fortran: Fortran
  go: Go
  groovy: Groovy
  haml: HAML
  handlebars: Handlebars
  haskell: Haskell
  http: HTTP
  javascript: JavaScript
  julia: Julia
  livescript: Livescript
  lua: Lua
  markdown: Markdown
  nginx: Nginx
  perl: Perl
  php: PHP
  powershell: Powershell
  plain: Plain Text
  puppet: Puppet
  python: Python
  ruby: Ruby
  rust: Rust
  sass: SCSS
  shell: Shell
  smalltalk: Smalltalk
  sql: SQL
  stylus: Stylus
  swift: Swift
  tcl: Tcl
  twig: Twig
  xml: XML
  xquery: XQuery
  yaml: YAML
